### PR TITLE
Add ZKSwap

### PR DESCRIPTION
**Pull request by ZKSwap-fe**

### CODE REVIEW

**Comment by krzkaczor** [comment]
That's great. I guess data pipeline will fail now because tokens lack description in config.json but filling out project metada with code links is SUPER helpful because this is a part that takes most of my time. 

I'll try to get this merged ASAP (few days).

**Comment by ZKSwap-fe** [comment]
@krzkaczor Thanks for your quick reply. I've pushed a commit to add the missing tokens' information. But some tokens can't be found in coinpaprika. I've leave the IDs blank. Do I need to remove those tokens?

**Comment by krzkaczor** [comment]
@ZKSwap-fe yes, for now let's remove tokens missing from coinpaprika. We will switch to coingecko soon and then i can re-add them.

Tracked: https://github.com/krzkaczor/l2beat/issues/36

**Comment by ZKSwap-fe** [comment]
@krzkaczor I've removed those tokens. Hope you can switch to coingecko soon since BBTC's value is very large. Here's the list of tokens removed:
`BBTC, XDEX, MASK, FEI, TRIBE`

**Comment by ZKSwap-fe** [comment]
@krzkaczor I've noticed the conflict and force-pushed to resolve them. Can you have a look and get this merged?

**Comment by krzkaczor** [comment]
Oh, i've changed the base branch and i was about to resolve conflicts. Thanks for taking care of it. I am gonna merge it to a temp branch and run data pipeline now.

**Comment by krzkaczor** [comment]
@ZKSwap-fe I am diving more into details of zkSwap. I found this article: https://coinmarketcap.com/headlines/news/zksync-and-zkswap/ which has claims like `ZKS is not even a ZK rollup`. I was trying to verify this and I can't do too much because the implementation [source](https://etherscan.io/address/0x2f70f6d864f8f597a0ef57addf24323dfab5797f) is not verified on etherscan. That being said I found traces of data being submitted in zkswap explorer: https://zkswap.info/en/block/52126

Are you part of ZKSwap team? Any chance to get this code verified?

Btw. tmp deployment with zkSwap: https://l2beat-git-dev-krzkaczor.vercel.app/project/zkswap

**Comment by ZKSwap-fe** [comment]
@krzkaczor It was not 100% rollup. We've upgraded to 100% rollup on March 22nd. Before that, the pubdata was on zkswap.info (e.g. block [34768](https://api.zkswap.info/block/34768/pub-data)). After upgrading, all pubdata have been commited to ethereum (e.g. the pubdata of block 52126 you mentioned has been submitted [here](https://etherscan.io/tx/0x800d6d235b5458d9a3f827fde54ab6d95a3307a1f3fb1bc3e7a9c70fd8c571f0)).

Right now, we are preparing a contract upgrade. We will get the code verified once updrades done.

**Pull request merged**
